
---
sudo: false
language: c
compiler:
  - clang

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - make -C ASM_OLD
  - make -C VM_OLD

addons:
  apt:
    packages:
      - gcc-multilib
