sudo: false
language: rust

os:
  - osx
 
compiler:
  - clang

rust:
  - nightly
  - stable
  - beta

env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

script:
  - rustc --version
  - make version
  - make
