sudo: false
language: rust

os:
  - linux
  - osx
 
compiler:
  - clang

rust:
  - nightly
  - stable
  - beta

env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

script:
  - rustc --version
  - make version
  - make

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - clang
