sudo: false
language: rust

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-4.9']
      env: COMPILER=g++-4.9  
    - os: linux
      compiler: clang
      addons:
      apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: clang
      env: COMPILER=clang++

rust: 
  - nightly
  - stable
  - beta

env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

os:
  - linux
  - osx

script:
  - CC --version
  - rustc --version
  - make

addons:
  apt:
    packages:
      - gcc-multilib
