sudo: false
language: rust

compiler:
  - clang
    
os:
  - linux
  - osx
        
rust:
  - nightly
  - stable
  - beta

env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

script:
  - rustc --version
  - make

addons:
  apt:
    packages:
    - gcc-multilib
