sudo: false
language: rust
compiler:
  - clang
  - gcc
rust: 
  - nightly
  - stable
  - beta

# Only while clippy is failing
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - PATH="$PATH:$TRAVIS_BUILD_DIR/target/debug"
cache:
  directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

os:
  - linux
  - osx

script:
  - make

addons:
  apt:
    packages:
      - gcc-multilib
