---
sudo: false
language: rust
rust:
  - stable
  - nightly
  - beta

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

script:
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - gcc-multilib

