---
sudo: false
language: rust
rust:
  - stable
  - nightly
  - beta

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install valgrind; fi

script:
  - cargo build
  - RUST_BACKTRACE=1 cargo test
  - valgrind --leak-check=full --log-file="valgrind.log" ./target/debug/asm_test
  - cat valgrind.log
  # NB: OSX has a lot of ObjC allocated memory still reachable, but that's not our bussiness.
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cat valgrind.log | grep "no leaks are possible"; fi

addons:
  apt:
    packages:
      - gcc-multilib
      - valgrind
