.TH ASM 1 2016-07-15 asm
.SH NAME
asm \- compile a champion.s to champion.cor.
.SH SYNOPSIS
.B asm\fI \fR<\fIfile.s\fR>
.SH DESCRIPTION
.B asm
Asm (Assembler) is coreware compiler.

.SH AUTHOR
Written by Alexis Hamouda <lexouu77@users.noreply.github.com>, adjivas <adjivas@users.noreply.github.com>, morgane <mdelmas@users.noreply.github.com> and Ashbury711 <ashbury711@users.noreply.github.com>.
